### ISSUE TITLE
Template file

### ISSUE THREAD

**Issue by ramonskovitch** [davidgohel/officedown#10]
is it possible to still call a template style file as it is in the usual
word_doc output
e.g.
output:
  word_document:
    reference_docx: ../styleref/my_style.docx

thank you

**Comment by cderv** [comment]
Hi, 

`officedown::rdocx_document` pass its arguments in `...` to `rmarkdown::word_document`, so yes it should work to pass a reference doc to be used by pandoc. If it does not work it would be interesting to know what is going wrong.


did you try it already ?

**Comment by ramonskovitch** [comment]
Hi, Thank you for replyingYes I tried. But not sure where in the yaml to put the reference_docx = filename.docx. it fails if I put it before the output: statement or as an indented below the rdocx output statement.Will explore more today knowing it should work. Any suggestions appreciated though.Regards DanSent via the Samsung Galaxy Note9, an AT&T 4G LTE smartphone
-------- Original message --------From: Christophe Dervieux <notifications@github.com> Date: 9/13/19  21:58  (GMT+10:00) To: davidgohel/officedown <officedown@noreply.github.com> Cc: ramonskovitch <nebula60@gmail.com>, Author <author@noreply.github.com> Subject: Re: [davidgohel/officedown] Template file (#10) Hi,
officedown::rdocx_document pass its arguments in ... to rmarkdown::word_document, so yes it should work to pass a reference doc to be used by pandoc. If it does not work it would be interesting to know what is going wrong.
did you try it already ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/davidgohel/officedown/issues/10?email_source=notifications\u0026email_token=AAOR7CB4Q2QOPVJADG5BJX3QJN56ZA5CNFSM4IWMHTRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6UZXGQ#issuecomment-531209114",
"url": "https://github.com/davidgohel/officedown/issues/10?email_source=notifications\u0026email_token=AAOR7CB4Q2QOPVJADG5BJX3QJN56ZA5CNFSM4IWMHTRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6UZXGQ#issuecomment-531209114",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ramonskovitch** [comment]
After some  more trials:

This works for word_doc output:
output:
  word_document:
    #reference_docx: ../styleref/undp_style-secnums.docx
    #reference_docx: ../styleref/undp_style.docx
    pandoc_args: --reference-doc=../styleref/undp_style.docx

So I am confident it is the correct pandoc_arg parameter
However in this scenario:
output: 
  officedown::rdocx_document
  pandoc_args: --reference-doc=../styleref/undp_style.docx

there is and error:
 Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: mapping values are not allowed in this context at line 6, column 14
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted

**Comment by davidgohel** [comment]
You can use the following:


```
---
title: "Habits"
output:
  officedown::rdocx_document:
    reference_docx: you-doc.docx
---
```

You can read https://bookdown.org/yihui/rmarkdown/word-document.html to learn more about this.
