### ISSUE TITLE
Math font in rdocx_document

### ISSUE THREAD

**Issue by fa-rzam** [davidgohel/officedown#100]
First, you so much for the combination of flextable, officedown, and officer. They're of great help. I am trying to generate equations with rdocx_document template and noticed that the equation fonts do not follow the word template I've created (I set it to Garamond-Math but they revert back to Calibri-Math). The fonts show Garamond-Math if I knit the document using word_document, I was wondering if there is any way to set the equation font in officedown. Thanks!

**Comment by davidgohel** [comment]
Hello

No, sorry, officedown does not manage equations but rmarkdown or pandoc
