### ISSUE TITLE
officedown::rpptx_document doesn't work

### ISSUE THREAD

**Issue by jixing475** [davidgohel/officedown#11]
## error information

> Quitting from lines 31-32 (test.rmd) 
Error in if (layout == "full_slide") { : argument is of length zero
Calls: <Anonymous> ... knit_print.dml -> get_content_layout -> withVisible -> _f
Execution halted

## lines 31-32 code
```{r plot1}
dml(plot(pressure))
```

## sessionInfo

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15

what's wrong?

**Comment by davidgohel** [comment]
this should now be solved. You need to update officer and rvg packages from CRAN (at this time, binaries are not yet build but I think you already got them and that's why you met that issue)

Thanks for letting me know.
