### ISSUE TITLE
Support {.unlisted .unnumbered} to exclude headings from table of contents

### ISSUE THREAD

**Issue by warnes** [davidgohel/officedown#111]
Pandoc allows a heading to be excluded from the table of contents by adding ` {.unlisted .unnumbered}` (see https://bookdown.org/yihui/rmarkdown-cookbook/toc-unlisted.html).

Unfortunately, this doesn't seem to be supported by `officedown::rdocx_document`.

Markdown code (Replace "'" with "`" to use):
```
---
title: "Untitled"
author: "Author"
date: "`r Sys.Date()`"
output: officedown::rdocx_document
---

'''{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
'''

# Table of Contents  {.unlisted .unnumbered}

<!---BLOCK_TOC--->

# One 

text

# One-A

more text

# Two

other text

## Two-A

more other text

## Two-B

all done
```

![image](https://user-images.githubusercontent.com/6144863/236959771-9191dc49-8fb0-4085-8208-635758ca9ca6.png)

**Comment by RichardMeyer-Eppler** [comment]
The table of contents is generated by Word on the basis of the styles defined in your reference.docx file. For each ToC, you can select the styles to include (e.g. Heading 1 and Heading 2) and assign the depth level. As far as I know, Word does not allow excluding specific headings on an individual basis (if they use a style that is included in the ToC definition).

The default formatting style will only include heading levels 1-3 in the table of contents. This means that you can use heading levels 4-5 in your mardown file and they will not display in the Word output. As usual, the formatting for these headings is defined through their styles in the reference.docx file.

In the example above, simply replace `# Table of Contents  {.unlisted .unnumbered}` with `#### Table of Contents` and format the style `Heading 4` in your reference.docx file.

**Comment by davidgohel** [comment]
Thanks @RichardMeyer-Eppler 

I think you are right. I tried with `rmarkdown::word_document()` and got the same result. So it's a normal behavior and `rdoc_document()` does not drop this feature. 



`````
---
title: "Untitled"
author: "Author"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Table of Contents  {.unlisted .unnumbered}

<!---BLOCK_TOC--->

# One 

text

# One-A

more text

# Two

other text

## Two-A

more other text

## Two-B

all done

`````

<img width="1073" alt="Capture d’écran 2023-05-20 à 10 18 38" src="https://github.com/davidgohel/officedown/assets/4331618/7ff2b216-fcf4-48d4-b4d6-a67ed15da71a">
