### ISSUE TITLE
Using chunk_page_break in a loop

### ISSUE THREAD

**Issue by tjane1596** [davidgohel/officedown#12]
Hi, 

I am in the process of creating a mail merge with R Markdown. I have an R script to scan a Contact List which inputs the Rmd document (Letter Template) to produce letters for each individual on the Contact List.

Another loop is written within the Rmd document that reads 3 data frames to produce 3 tables. For example:

1. Store Details
2. Financial Details
3. Transactions 

So far, everything is producing beautifully but the only problem is the table layout. A letter for each contact may have 2 or more Stores and so, 6 or more tables all with varying numbers of rows. 

I was hoping that by incorporating chunk_page_break_ at the end of the loop it would create a new page for the next 3 tables. 

I have attempted to create blank space that separates the tables but that does not work well. 

Would you be able to assist me with this? Thank you in advance!

**Comment by davidgohel** [comment]
I have created 2 new functions `knit_print_block` and `knit_print_run` to ease usage of officedown with officer blocks and runs functions.

````````
---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.cap = TRUE)
library(officedown)
library(officer)
```

```{r results='asis', echo=FALSE}
for(i in 1:4){
  knit_print_run(
    run_pagebreak()
  )
}
```


````````

Note you don't need officedown for that (add `\newpage` in R Markdown)
