### ISSUE TITLE
In-consistencies with the officeverse bookdown

### ISSUE THREAD

**Issue by jimewu** [davidgohel/officedown#122]
In the [Chapter 5 officedown for Word](https://ardata-fr.github.io/officeverse/officedown-for-word.html), the R function for the tag `BLOCK_LANDSCAPE_START` and `BLOCK_LANDSCAPE_STOP` are `block_section_continuous` and `block_section_landscape`, respectively. However, now those 2 fuctions are not available, and I found that it is actually `block_section(prop_section(type = "continuous"))` for the tag `BLOCK_LANDSCAPE_START`, and `block_section(prop_section(page_size = page_size(orient = "landscape")))` for the tag `BLOCK_LANDSCAPE_STOP`. Please update relevant content. 

Thanks for your support.

**Comment by davidgohel** [comment]
Thanks, I have updated the book, it should be available in few minutes
