### ISSUE TITLE
Issue with out.width not affecting image size in officedown::rdocx_document

### ISSUE THREAD

**Issue by lizhiwei1994** [davidgohel/officedown#144]
I am trying to generate a Word document with R using the `officedown::rdocx_document` output format. When I use the standard `output: word_document` option, I can easily control the size of images in the output by setting different values for the `out.width` parameter in my RMarkdown document. However, when I switch to `officedown::rdocx_document`, the images are not resizing as expected. No matter what value I set for `out.width`, the image size remains unchanged.

Here's a minimal reproducible example:

**Using `output: word_document` option**:

````
---
output: word_document
---

```{r setup, include=FALSE}
library(officedown)
library(officer)
```

### out.width='10%'

```{r echo=FALSE, out.width='10%'}
boxplot(1:8)
```

### out.width='90%'

```{r echo=FALSE, out.width='90%'}
boxplot(1:8)
```

````

**Using `officedown::rdocx_document` option**:
````
---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
library(officedown)
library(officer)
```

### out.width='10%'

```{r echo=FALSE, out.width='10%'}
boxplot(1:8)
```

### out.width='90%'

```{r echo=FALSE, out.width='90%'}
boxplot(1:8)
```

````

**Comment by davidgohel** [comment]
I read: 

- https://stackoverflow.com/questions/78874809/issue-with-out-width-not-affecting-image-size-in-officedownrdocx-document
- https://github.com/davidgohel/officedown/discussions/142

I did not work on it yet, you don't need to open duplicates every day until I find a fix

**Comment by lizhiwei1994** [comment]
Thank you for your response and for looking into this issue. I apologize for any inconvenience caused by the duplicate posts. I appreciate your efforts in addressing this problem, and I'll wait for your update whenever you have a chance to work on it.

Thanks again for your time and help!

Best regards,

zhiwei

**Comment by davidgohel** [comment]
it should be OK now

**Comment by TheDom42** [comment]
I believe this fix broke a different functionality: `out.width` and `out.height` can also be non-numeric in other cases - you can actually change the dimensions of the plot with other units (such as cm) - see https://yihui.org/knitr/options/:

> out.width, out.height: (NULL; character) Width and height of the plot in the output document, which can be different with its physical fig.width and fig.height, i.e., plots can be scaled in the output document. Depending on the output format, these two options can take special values. For example, for LaTeX output, they can be .8\\linewidth, 3in, or 8cm; for HTML, they may be 300px. For .Rnw documents, the default value for out.width will be changed to \\maxwidth, which is defined [on this page.](https://yihui.org/knitr/demo/framed/) It can also be a percentage, e.g., '40%' will be translated to 0.4\linewidth when the output format is LaTeX.

I encountered the error when using a script from a project using an earlier officedown version. I had specified the chunk options: `out.height="5.5cm", out.width="8.27cm"`
My render broke with the following error and backtrace:

```r
Error in `fig.width * fig.out.width`:
! non-numeric argument to binary operator
Backtrace:
     ▆
  1. └─rmarkdown::render(...)
  2.   └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3.     └─knitr:::process_file(text, output)
  4.       ├─xfun:::handle_error(...)
  5.       ├─base::withCallingHandlers(...)
  6.       └─knitr:::process_group(group)
  7.         └─knitr:::call_block(x)
  8.           └─knitr:::block_exec(params)
  9.             └─knitr:::eng_r(options)
 10.               ├─base::unlist(sew(res, options))
 11.               ├─knitr::sew(res, options)
 12.               └─knitr:::sew.list(res, options)
 13.                 └─base::lapply(x, sew, options, ...)
 14.                   ├─knitr (local) FUN(X[[i]], ...)
 15.                   └─knitr:::sew.recordedplot(X[[i]], ...)
 16.                     ├─knitr:::in_base_dir(run_hook_plot(files[[1]], reduce_plot_opts(options)))
 17.                     │ └─knitr:::in_dir(d, expr)
 18.                     └─knitr:::run_hook_plot(files[[1]], reduce_plot_opts(options))
 19.                       └─officedown (local) hook(x, options)
 ```

I assume that

https://github.com/davidgohel/officedown/blob/10d14c7bced360fb2eee33344b46ce8e6eccfb6c/R/hooks.R#L73C1-L74C44

breaks when the chunk options are not numerical or (now) in %.

**Comment by TheDom42** [comment]
As a workaround (until this is properly identified and fixed) and if you want to stay with other units than the default inches, this should fix it:

https://stackoverflow.com/a/68442017

> As a side-answer, note that you can also use metric-system units using ggplot2::unit():

```r
library(ggplot2)
knitr::opts_chunk$set(fig.width=unit(18,"cm"), fig.height=unit(11,"cm"))
```
