### ISSUE TITLE
Block docx

### ISSUE THREAD

**Issue by melTr** [davidgohel/officedown#16]
Hi
Thanks for your work. I will be able to get closer to my goal!
After trial and errors (and reading [this](https://github.com/rstudio/shiny/issues/1626#issuecomment-547029936), I finally was able to insert docx in my document, but with this syntax
`<!---BLOCK_POUR_DOCX{docx_file: 'test.docx'}---> `
instead of mentioned snippet in your doc
`<!---BLOCK_POUR_DOCX{docx_file:'path/to/docx'}--->`
Small detail but useful for beginner to know.
Thanks
Mel

**Comment by davidgohel** [comment]
A comment has been added explaining it's YAML format and YAML format wants a space. 

https://github.com/davidgohel/officedown/blob/master/vignettes/officer.Rmd#L73
