### ISSUE TITLE
Syntax and args for chunk_text

### ISSUE THREAD

**Issue by melTr** [davidgohel/officedown#17]
Hi
Do you mind to give a list of accepted arguments and the correct syntax? 
I tried this but it doesn't work. Your examples from readme works fine in my document, so I guess I have no problem else than syntax.
 

Thanks

**Comment by davidgohel** [comment]
The manuals and documentation will evolve soon.

For now, you can read 

https://github.com/davidgohel/officedown#chunks
https://github.com/davidgohel/officedown#blocks
https://github.com/davidgohel/officedown#sections-blocks

and see manual corresponding to *R function*

**Comment by melTr** [comment]
Oups, just saw the code was not appearing. But after some tests and re-tests, I can confirmed this
`<!---CHUNK_TEXT{str: 'worded', underlined: true}--->` doesn't work however 
this works
`<!---CHUNK_TEXT{str: 'worded', bold: true}--->`
So I'm wondering what is wrong.
Thanks.

**Comment by davidgohel** [comment]
CHUNK_TEXT has been removed. Now you will have to use `r ftext(...)` instead.
