### ISSUE TITLE
Tables of figures and tables do not render correctly

### ISSUE THREAD

**Issue by kestrel99** [davidgohel/officedown#20]
Hi,

In the demonstration bookdown included with the package, the Table of Figures and Table of Tables do not render but instead report `"No table of contents entries found."` (See attached output). 

Is there a workaround for this? It's pretty much the only thing stopping me using `officedown` in production. (This together with `officer` and `flextable` represent a phenomenal set of tools, thanks for all the hard work!)

[bookdown.docx](https://github.com/davidgohel/officedown/files/4586693/bookdown.docx)

**Comment by davidgohel** [comment]
I can not reproduce what you are describing. A `sessionInfo()` may help.
There are differences in your document, i.e. the section content is not the same. Did you modify something? 

---
On my side:

After having click "Yes" to this windows:

<img width="422" alt="Capture d’écran 2020-05-06 à 15 18 47" src="https://user-images.githubusercontent.com/4331618/81181626-04bf9500-8fad-11ea-9124-cf2503e2c27d.png">

I get that result:

<img width="1080" alt="Capture d’écran 2020-05-06 à 15 18 59" src="https://user-images.githubusercontent.com/4331618/81181655-0f7a2a00-8fad-11ea-9f9c-4dd76e54a6d5.png">

**Comment by kestrel99** [comment]
Starting in a new session with nothing loaded:

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252    LC_MONETARY=English_Germany.1252
[4] LC_NUMERIC=C                     LC_TIME=English_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.0        magrittr_1.5         officer_0.3.9        officedown_0.0.6.018 knitr_1.28          

loaded via a namespace (and not attached):
 [1] zip_2.0.4         Rcpp_1.0.4.6      compiler_3.6.2    pillar_1.4.3      tools_3.6.2       digest_0.6.25    
 [7] packrat_0.5.0     uuid_0.1-4        evaluate_0.14     memoise_1.1.0     lifecycle_0.2.0   tibble_3.0.1     
[13] gtable_0.3.0      pkgconfig_2.0.3   rlang_0.4.6       rstudioapi_0.11   yaml_2.2.1        xfun_0.13        
[19] withr_2.1.2       dplyr_0.8.5       stringr_1.4.0     xml2_1.3.1        vctrs_0.2.4       gdtools_0.2.2    
[25] systemfonts_0.2.0 tidyselect_1.0.0  grid_3.6.2        glue_1.4.0        R6_2.4.1          rvg_0.2.4        
[31] rmarkdown_2.1     bookdown_0.18.1   farver_2.0.3      purrr_0.3.4       scales_1.1.0      htmltools_0.4.0  
[37] ellipsis_0.3.0    assertthat_0.2.1  colorspace_1.4-1  labeling_0.3      stringi_1.4.6     munsell_0.5.0    
[43] crayon_1.3.4     
```

**Comment by kestrel99** [comment]
Latest GitHub version, fresh session and unmodified example gives the same...
[bookdown.docx](https://github.com/davidgohel/officedown/files/4587133/bookdown.docx)

**Comment by davidgohel** [comment]
It's working as expected for me. It seems to me you did not click "Yes" to refresh the calculated fields (TOC, etc.)

**Comment by kestrel99** [comment]
This is really odd. I have reinstalled officedown and all dependencies on top of a fresh version of R 4.0.0 - but same result. I see the following dialog and click "Yes":

<img width="422" alt="dialog1" src="https://user-images.githubusercontent.com/9568350/81191492-5ec65780-8fb9-11ea-9ed3-ebeb369169b7.png">

Then I have two of these:

<img width="406" alt="dialog2" src="https://user-images.githubusercontent.com/9568350/81191532-6980ec80-8fb9-11ea-9e42-f463602fbcde.png">

Word version info, in case that has anything to do with it...

<img width="398" alt="about" src="https://user-images.githubusercontent.com/9568350/81191584-79003580-8fb9-11ea-8a4a-49e4f5edabac.png">

**Comment by davidgohel** [comment]
thanks for this... I may need time (or not...), I need to test with this office version and I don't have it...

**Comment by kestrel99** [comment]
No worries! Thanks. In the meantime I'll keep trying workarounds.

**Comment by kestrel99** [comment]
An update on this - tried it with a fresh install of R 4.0.0 on MacOS Catalina 10.15.4 and Word for Mac (version 16.36), latest versions of `officer`, `flextable` and `officedown` from GitHub. Same result as on Windows: no tables of figures or tables (also with the same dialogs when opening the document).

**Comment by davidgohel** [comment]
Could you try to replace the instruction? I think it will solve the issue. (You need to reinstall the latest versions of officer and officedown)

```
<!---BLOCK_TOC{style: 'Image Caption'}--->
```

with 

```
<!---BLOCK_TOC{style: 'Image Caption', separator: ','}--->
```

**Comment by kestrel99** [comment]
It works! Brilliant, thank you. Was it caused by a change in Word?

One or two related questions/comments:
- Table cross-references showing up as "Error! Bookmark not defined." e.g. for `\@ref(tab:mtcars)`
- Table numbers not showing up in the list of tables (maybe I missed a setting?)

**Comment by davidgohel** [comment]
No, this is a regional setting. I saw the case a long time ago with someone that was on a *Canadian* setting. I only know it happens but doesn't know how to detect it (I am sure it is simple, I just don't know where to look).

For the point 1. Wait a little bit; this is WIP at the moment and things could move (I am fortifying things before a cran release soon). 

For the point 2, you probably need to "select All" and type F9 to refresh computed fields - or not, maybe just a temporary bug...

(In general try to open one single ticket for one issue :) )

**Comment by kestrel99** [comment]
Thanks! In that case I'll wait for the CRAN release...

**Comment by davidgohel** [comment]
About your two last questions. It is now fixed. That was a bug

**Comment by somkamalin** [comment]
I have same issue as:

"List of tables
No table of figures entries found."

This is for flextable.

my code is :       # as suggested above.
#installed officer,officedown  from CRAN, today.
