### ISSUE TITLE
Header and footer content only appears in last section when using section blocks

### ISSUE THREAD

**Issue by RichardMeyer-Eppler** [davidgohel/officedown#21]
When using sections blocks with BLOCK_LANDSCAPE_START and BLOCK_LANDSCAPE_STOP, I have noticed that the reference document's header and footer content will only get displayed in the last section (because Word's "Link to previous" option is disabled in all headers and footers). Is there a way to change this behavior? Maybe it would be possible to add this as an argument to the section blocks?

An easy way to replicate the issue:

1. Add a page number to the footer of your template.docx
2. `rmarkdown::render_site("bookdown")`
3. The resulting Word document "bookdown.docx" will only have page numbers in the very last section (i.e. the content of "05-plots.Rmd")

**Comment by davidgohel** [comment]
Thanks, that is now fixed.
