### ISSUE TITLE
Figure and table numbers do not show up consistently in lists of figures and tables

### ISSUE THREAD

**Issue by kestrel99** [davidgohel/officedown#22]
When generating lists of tables and figures, figure and table numbers appear inconsistently or not at all. In the demo, I have substituted the original TOC code with:

`<!---BLOCK_TOC{style: 'Image Caption', separator: ','}--->`

`<!---BLOCK_TOC{style: 'Table Caption', separator: ','}--->`

I didn't change the demo code in any other way. In my own tests, I can't get figure and table numbers to appear in the lists at all. Hyperlinks in the text display as expected (e.g. using `\@ref(fig:ts-plot)`.)

Notice that some figure and table numbers appear and others do not.

[bookdown.docx](https://github.com/davidgohel/officedown/files/4633501/bookdown.docx)

**Comment by davidgohel** [comment]
Did you refresh the fields?

**Comment by davidgohel** [comment]
I can't reproduce your issue

**Comment by kestrel99** [comment]
> Did you refresh the fields?

A manual refresh works! Apologies, that should have been obvious.
