### ISSUE TITLE
Dashes "-" in figure/table ids produce an error when referenced

### ISSUE THREAD

**Issue by dirkschumacher** [davidgohel/officedown#23]
It seems when using "-" (and maybe other special characters) as table/figure ids, referencing them is not possible anymore using the `\@ref(id-dash)` syntax.

**Comment by dirkschumacher** [comment]
Strange. I cannot reproduce it. So nevermind. I will try to find a reprex or it is fixed.

PS: There is a reference to `id-dash`. Is this a leftover from debugging? https://github.com/davidgohel/officedown/blob/86e227f65e21b2aca40a575181cb68e9c6dcac8d/inst/examples/minimal_word.Rmd#L11

**Comment by davidgohel** [comment]
> reference to id-dash

Yes, I added that to test your issue and forget to drop it :( 
However, it might be good it is in an example so that it can be tested
