### ISSUE TITLE
support table of regression results 

### ISSUE THREAD

**Issue by maoyimin** [davidgohel/officedown#25]
I hope this package can support tables of regression results built by packages like stargazer.

**Comment by davidgohel** [comment]
No

Features are documented on the README. page: https://github.com/davidgohel/officedown#word

You can use `flextable::as_flextable` for creating tables from lm and glm objects but that's all I have for now.

**Comment by Alaburda** [comment]
For lm/glm objects and officedown compatibility, you could try using the [broom](https://cran.r-project.org/web/packages/broom/vignettes/broom.html) package. The output will not be ideally the same but broom turns lm objects into data.frames that you can then use in officedown.
