### ISSUE TITLE
Links to file paths containing special characters do not work

### ISSUE THREAD

**Issue by jarauh** [davidgohel/officedown#30]
I want to link to a file (or directory) containing special characters:
```r
---
output:
  officedown::rdocx_document: default
  bookdown::word_document2: default
---
[works](C:/Users/Public)
[doesn't work](C:/Users/Public/Umläüt)
```
The code produces an invalid docx-file with `officedown-0.2.0`, while it does work with `bookdown`.

**Comment by davidgohel** [comment]
Thanks, I can reproduce on Windows

**Comment by davidgohel** [comment]
thanks for reporting that

It is fixed now, issue was happening with officer, not officedown. 

You need to run `remotes::install_github("davidgohel/officer")` to install the github version until it's been submitted to CRAN
