### ISSUE TITLE
flextable and officedown: location by placeholder

### ISSUE THREAD

**Issue by Pindar777** [davidgohel/officedown#33]
I want to write rmd and place the result inside a table with predefined column-widths.
At the moment  a code chunk for a flextable seems to be the only option at hand.
I designed a "pandoc-only-template" which should be used to get the right locations for the flextable. However, this has no effect on the flextable. Perhaps there is a solution with ph_with inside the chunk? But what to do with the "x" argument, since we are inside/generating an rpptx object via rmd-file.

```{r layout='Textchart_2h_B', ph=officer::ph_location_type(type = "body", position_right=TRUE, position_top = FALSE)}
ft1 <- flextable(head(iris))
arrW <- dim_pretty(ft1)
ft1 <- width(ft1, width = arrW$widths)
ft1
# has not effect
```
Cheers

**Comment by davidgohel** [comment]
This is not implemented. I recommend you to use the documented parameters of flextable, see https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#powerpoint-chunk-options

**Comment by Pindar777** [comment]
@davidgohel ft.left and ft.top are very helpful for reaching my goal.
In the docs I guess it should read {r ft.left=1, **ft.top**=2}.

Cheers
