### ISSUE TITLE
manipulating page headers and footers

### ISSUE THREAD

**Issue by heor-andreas** [davidgohel/officedown#39]
Hi David,

I've got a reference document that has a page header and footer but I would like to change them for the report I create with officedown. So for each report they should take on the title of the officedown document.
I found the headers_replace_all_text() function of officer and could create my word document using Rmd and officedown and in a second pass run the officer::headers_replace_all_text() function to change the header.
But I was wondering if there's a quicker way to do this in the Rmd file itself? (I can't see a way to get the headers_replace function to work from within the Rmd file)

**Comment by davidgohel** [comment]
Hello,

No sorry.

**Comment by mtkerbeR** [comment]
I solved a similar problem using a customized knit function - maybe this could help here as well:

https://bookdown.org/yihui/rmarkdown-cookbook/custom-knit.html

**Comment by heor-andreas** [comment]
> I solved a similar problem using a customized knit function - maybe this could help here as well:
> 
> https://bookdown.org/yihui/rmarkdown-cookbook/custom-knit.html

Thanks for pointing this out.
That looks promising but it looks like I can only get the rmarkdown::render function to run within the knit parameter. Did you manage to get other functions wrapped within the knit?

**Comment by mtkerbeR** [comment]
The following code works for me (please note, the empty lines within knit-function and there seems to be a parsing problem if you write comments within the code).

The general strategy is

1. Generate the document via officedown - rmarkdown::render
2. Open the resulting document, edit it and print/save it

This is inspired by:
[https://stackoverflow.com/questions/39713618/knitr-hook-to-postprocess-pdf-output](https://stackoverflow.com/questions/39713618/knitr-hook-to-postprocess-pdf-output)

[https://stackoverflow.com/questions/28500096/r-markdown-variable-output-name/28785774#28785774](https://stackoverflow.com/questions/28500096/r-markdown-variable-output-name/28785774#28785774)
```
---
date: "2020-10-11"
author: "Your Name"
title: "officedown template"

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_format = officedown::rdocx_document(),
      envir = globalenv()
    )
    
    filename <- paste0(basename(tools::file_path_sans_ext(input)), '.docx')
  
    doc <- officer::read_docx(filename)
    
    officer::body_add_par(doc, "... and this is written via customized knit")
    
    print(doc, filename)
    
  })
---

This is a text via officedown.
```

**Comment by heor-andreas** [comment]
> The following code works for me (please note, the empty lines within knit-function and there seems to be a parsing problem if you write comments within the code).
> 
> The general strategy is
> 
> 1. Generate the document via officedown - rmarkdown::render
> 2. Open the resulting document, edit it and print/save it
> 
> This is inspired by:
> https://stackoverflow.com/questions/39713618/knitr-hook-to-postprocess-pdf-output
> 
> https://stackoverflow.com/questions/28500096/r-markdown-variable-output-name/28785774#28785774
> 
> ```
> ---
> date: "2020-10-11"
> author: "Your Name"
> title: "officedown template"
> 
> knit: (function(input, ...) {
>     rmarkdown::render(
>       input,
>       output_format = officedown::rdocx_document(),
>       envir = globalenv()
>     )
>     
>     filename <- paste0(basename(tools::file_path_sans_ext(input)), '.docx')
>   
>     doc <- officer::read_docx(filename)
>     
>     officer::body_add_par(doc, "... and this is written via customized knit")
>     
>     print(doc, filename)
>     
>   })
> ---
> 
> This is a text via officedown.
> ```

Thanks again, that works well for me.
I actively avoided the empty lines when I wrote my code...

do you think there is a way to access the params or any part of the YAML header through this function?

here's what I tried, but it looks like the params isn't being picked up. (it works fine printed in the document).
there's obviously the way to specify the two parameters as part of the function call like: (function(input, short_title="My short title",...) {} but I guess it would be more convenient as a parameter
```
---
date: "`r Sys.Date()`"
title: "Study Report"
output: 
  officedown::rdocx_document:
    reference_docx: template.docx
params:
  short_title: "My Study short title"
  document_type: "My Study Report"
 
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      envir = globalenv()
    )

    filename <- paste0(basename(tools::file_path_sans_ext(input)), '.docx')
    
    doc <- officer::read_docx(filename)

    officer::headers_replace_all_text(doc, "< Insert Short study title >", params$short_title)

    print(doc, filename)

  })

```

**Comment by mtkerbeR** [comment]
Interesting question - I think "yes", there should be a way to "Access YAML parameters in a customized knitr-function" 

However, as this question seems to be unrelated to officedown, I would suggest to pose this question at another place like stackoverflow (probably together with a more general example using hml rather than officedown/officer to increase chances of a good/fast answer).
