### ISSUE TITLE
Table/figure captions linked to section name/number

### ISSUE THREAD

**Issue by imagema** [davidgohel/officedown#40]
Currently seems that table and figures are captioned sequentially 1:n.  Is there a way to make the captioning link to the section in which they are located (e.g. Table 3.1, 3.2.. 3.n for tables located in section 3, or even Table A.1, A.2 for tables located in a document appendix), as is possible in Word?

**Comment by davidgohel** [comment]
It is possible, but as you would not use the default behavior, you would have to define yourself the component of your captions. 

I've added an illustration here: https://ardata-fr.github.io/officeverse/officedown-for-word.html#table-caption-linked-to-section-number

Please, let me know if not clear.

Note that it is recommended to create a hook to make that code easier to use/less verbose with `knit_hooks$set`.

**Comment by imagema** [comment]
Thanks vm David. Will check this out and revert if any queries.

**Comment by bishun945** [comment]
@davidgohel I tried the illustration you linked but got the error output in the word document.

I just copied your demo codes and append them after of `01-intro.Rmd` and click `Build book`.

> Figure **_Error! No text of specified style in document._** - 1: truc machin chose

It seems that the auto-number `1` is correctly returned by `run_autonum` but failed to section number.

**Comment by bishun945** [comment]
Strange. I restarted my R studio and re-built it again. And it works. (Dont know why)
I also tested to add the first head caption like **Figure 1. 1** as follows: 
```
runs <- list(
  run_word_field("STYLEREF 1 \\s"),
  ftext(". "),
  run_autonum(seq_id = "tab", pre_label = "", post_label = "")
)
```
That is OK. Thanks for that illustration.

Another question that has puzzled me for a long time is about auto-number equations and cross-reference them. I know it may be inappropriate to discuss in this issue but can you give me some quick answers?

Thansk a lot.

**Comment by davidgohel** [comment]
> Another question that has puzzled me for a long time is about auto-number equations and cross-reference them. I know it may be inappropriate to discuss in this issue but can you give me some quick answers?

Please read: 

* https://ardata-fr.github.io/officeverse/officedown-for-word.html#cross-references
* https://ardata-fr.github.io/officeverse/officedown-for-word.html#add-runs

Open a new issue if you have an issue.
