### ISSUE TITLE
loop a list of tables with proper captions and sequence IDs

### ISSUE THREAD

**Issue by littlehifive** [davidgohel/officedown#43]
Hi David,

I am wondering if you could help me with the following issues when using `flextable` in `officedown`:

I have a list of multiple data frames. I'd like to print each data frame using `flextable(list[[i]])` and knit those to a word document. However, the `knitr` chunk header only allows me to set an overarching table caption and `for` loops don't quite work here. Is there a way to print all tables in the list at once and allow me to customize each table caption?

```
{r internal_reliability, tab.cap = "Internal reliability", tab.id = "internal_reliability"}

for (i in length(list)) {
  flextable(list[[i]]) %>%
  align(part = "all") %>%
  font(fontname = "Times", part = "all") %>% 
  bold(part = "header") %>%
  fontsize(size = 10, part = "body") %>% 
  set_table_properties(layout = "autofit")
}
```

Another issue is that in the table of content, it doesn't show the table id. It would be great if it shows Table 1: Descriptive statistics, and Table 2: Correlation matrix. See my set up below:

<img width="996" alt="Screen Shot 2020-10-23 at 2 26 43 PM" src="https://user-images.githubusercontent.com/26876926/97040344-c9555a80-153b-11eb-8ac3-06ed7f0e883b.png">

```
---
title: "`r params$set_title`"
author: "`r params$set_author`"
date: "`r Sys.Date()`"
params:
  printcode: no
  printwarning: no
  storecache: yes
  set_title: "Report"
  set_author: "Michael Wu"
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
    reference_docx: "MR_word_template.docx"
---

```{r setup, include = F}

# knitr global settings
knitr::opts_chunk$set(
  echo = TRUE, 
  fig.cap = TRUE,
  echo = params$printcode, 
  warning = params$printwarning, 
  cache = params$storecache,
  message = F,
  error = T,
  results="asis",
  tab.cap.style = "Table Caption",
  tab.cap.pre = "Table ",
  tab.cap.sep = ": ",
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ",
  fig.cap.sep = ": ")```

```
Thank you so much!

**Comment by davidgohel** [comment]
yes. All your questions are documented; see:

* https://davidgohel.github.io/flextable/reference/docx_value.html
* https://stackoverflow.com/questions/58173966/looping-flextables-in-r-markdown-documents-with-word-output/58174170#58174170
* https://davidgohel.github.io/flextable/articles/offcran/examples.html#looping-in-r-mardown-documents (it shows things with `htmltools_value` but the strategy is the same with `docx_value`)

For the second question, see:

* https://davidgohel.github.io/flextable/reference/set_caption.html 
* https://ardata-fr.github.io/officeverse/officedown-for-word.html#set-caption-label

**Comment by littlehifive** [comment]
Thanks for your help!

Following up on my second question:

I am able to get sequenced IDs for tables in text (either by setting the chunk header or using the `set_caption` function):
![Screen Shot 2020-10-23 at 11 38 02 PM](https://user-images.githubusercontent.com/26876926/97067172-cd5b9980-1588-11eb-9eb6-a4a38e2d9944.png)
e.g. ````{r descriptive, tab.cap="Descriptive statistics", tab.id = "descriptive"}`

But I can't get the IDs for the tables/figures in the ToC:
![Screen Shot 2020-10-23 at 11 38 52 PM](https://user-images.githubusercontent.com/26876926/97067181-e9f7d180-1588-11eb-83b6-5a3326a0d96c.png)

I am also not quite sure how that works (partially) in your [book](https://ardata-fr.github.io/officeverse/officedown-for-word.html#)), where the number 2 shows for "Figure 2", but 1&3 are not showing for "Figure 1" and "Figure 3". The table section also shows the same problem.
<img width="543" alt="Screen Shot 2020-10-23 at 11 39 45 PM" src="https://user-images.githubusercontent.com/26876926/97067190-0a279080-1589-11eb-9880-1a8c417df5e6.png">

Thank you so much for your kind help!

**Comment by davidgohel** [comment]
Could you open a separate issue and provide a full reproducible example? I can't help because I can't reproduce
