### ISSUE TITLE
Make it possible to customize font size in R code chunks

### ISSUE THREAD

**Issue by jranke** [davidgohel/officedown#45]
I was trying to edit the character style "Verbatim Char" in my Word instances (2010 and 2017) but I could not find it in the formatting styles dialogues, also not under a corresponding German style name.

So I was looking what to do, and found that it is much easier to just edit the word/styles.xml file, look for "Verbatim Char" and change the size "sz" from 22 to 20 and - voilá - the R code looks better and has less irritating line breaks.

I was wondering if this could be made configurable... I did not find an option in pandoc or rmarkdown, so I am filing the issue here, because this is the package I am actually using.

**Comment by davidgohel** [comment]
`Verbatim Char` is part of the default pandoc Word template. You can get it with this command:

```
pandoc --print-default-data-file reference.docx > reference.docx
```
A more simple soluton is to create a text style named `Verbatim Char` in Word. See https://ardata-fr.github.io/officeverse/office-documents-generation.html#word-document-styles

**Comment by jranke** [comment]
Thank you for your input. i was hoping for a solution where I neither need a reference document nor start up Word... But I will get by.

**Comment by davidgohel** [comment]
You can create formatted chunks of text, you can change a style to another style but you can not change or add styles. This may be implemented one day https://github.com/davidgohel/officer/issues/304
