### ISSUE TITLE
Word Output - file is corrupt and cannot be opened

### ISSUE THREAD

**Issue by mps9506** [davidgohel/officedown#49]
When submitting a new issue:

- [x] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [x] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

---

Hi,
First, thanks for officedown/officer and other amazing packages. I am having an issue rendering word documents, I'm not 100% sure if this is an officedown issue or perhaps rmarkdown/knitr. For reference, I'm using v 0.2.0 from CRAN. This is *possibly* related to #31.

## Issue

If the author yaml field includes an ampersand, I receive the following error after the word document is rendered:
![Screenshot 2020-11-12 122323](https://user-images.githubusercontent.com/11282246/98980938-f1a0fb00-24e2-11eb-87fe-9299f501367e.png)

Click "OK" and get the following:
![Screenshot 2020-11-12 122403](https://user-images.githubusercontent.com/11282246/98981007-05e4f800-24e3-11eb-8342-16fdd0b6326e.png)

Click "Yes" and it will open as a new (unsaved) word document, and everything looks good. I just have to save as a new file.

## Reprex

Here is the .Rmd that I directly knit from:
```
---
author:
  - First Author ^1,a^, Second Author ^1^
  - ^a^ Texas A&M University
  - ^a^ Corresponding author, first.author@tamu.edu
title: "Something about *Escherichia coli*"
abstract: |
  |  This is the abstract.
  |  
  |  It consists of two paragraphs.
output: 
  officedown::rdocx_document
---


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu pulvinar arcu, quis aliquam dui. In at cursus ante. Vestibulum non sagittis lacus. Duis vitae iaculis dui. Vivamus tempor, nibh ut pretium tempus, enim lorem dignissim quam, at euismod massa magna at magna. 
```

If I remove the ampersand it knits just fine and produces an error free word doc. I've tried different combinations of escaping the ampersand, quotes, etc.  

The corrupted file is attached:
[demo.docx](https://github.com/davidgohel/officedown/files/5532598/demo.docx)

## Session Info

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        packrat_0.5.0     digest_0.6.25     R6_2.4.1          magrittr_1.5      officedown_0.2.0  evaluate_0.14    
 [8] zip_2.1.1         gdtools_0.2.1     rlang_0.4.7       uuid_0.1-4        xml2_1.3.2        rmarkdown_2.3     tools_3.6.2      
[15] officer_0.3.15    xfun_0.15         yaml_2.2.0        compiler_3.6.2    systemfonts_0.3.2 rvg_0.2.4         memoise_1.1.0    
[22] htmltools_0.5.0   knitr_1.29       
```

**Comment by davidgohel** [comment]
Thanks. I can reproduce!

**Comment by davidgohel** [comment]
Hello,

I found the issue, sorry for the time it took... The issue was in package `officer`. A new version is available on CRAN (binaries are not yet built but it should be in few days).

So to solve this issue, you have to install the new version of officer and it should be ok.
