### ISSUE TITLE
New Line

### ISSUE THREAD

**Issue by keithhurley** [davidgohel/officedown#5]
Interested in how to create a chunk to add a new line much like  adds a pagebreak.

**Comment by davidgohel** [comment]
It does not exists but that's a very good suggestion

**Comment by davidgohel** [comment]
The new version is allowing this syntax for line break:

```
This is a dummy text, `r officer::run_linebreak()`this goes into a new line
```

**Comment by SchmidtPaul** [comment]
Do you think it is possible to define a custom command such as `\newline` with this? Ideal would be something like

``` r
\br <- `r officer::run_linebreak()`
```
Or maybe more like this stackoverflow question [R Markdown similar feature to "newcommand" in LaTex?](https://stackoverflow.com/questions/41655383/r-markdown-similar-feature-to-newcommand-in-latex):

``` r
\newcommand{\br}{`r officer::run_linebreak()`}
```

If not, is this the most efficient way of adding line breaks in an officedown document?
``````
``` r
br <- officer::run_linebreak()
```

`r br()`
``````

**Comment by davidgohel** [comment]
Yes it's probably possible, but I don't see much interest in that. Doesn't `\newline` works already—without officedown?



I think there is a mistake in your command. If you do `br <- officer::run_linebreak()`, then `br` is an object, don't add parenthesis.

```
`r br`
```

I think the most efficient way of adding line breaks (soft return, not a new paragraph) in an officedown document is as you suggested (but no parenthesis)
