### ISSUE TITLE
Style individual text elements with a style from the template docx

### ISSUE THREAD

**Issue by paurrodri** [davidgohel/officedown#51]
Thank you for the great work on this super useful package. 

I would like to ask if it is possible to style individual text elements with a style from the template Word document indicated in `reference_docx` field in the YAML header. 

I know individual text elements can be styled using `ftext` and `fp_text` e.g.:
```
Here is some normal text. `r ftext('But this sentence is red', fp_text(color = "red"))`
```

But instead of using specific font/color etc. properties as argument, is it possible somehow specify a style that is contained in the template/reference Word document? 

I have not found any documentation relative to this.

Thanks a lot!

**Comment by davidgohel** [comment]
Hello,

Here is a link: https://ardata-fr.github.io/officeverse/office-documents-generation.html#usage-with-rmarkdown

Nothing related to officedown, this job is done by pandoc so I did not reinvent the wheel ;)
