### ISSUE TITLE
broken (?) support for short captions `fig.scap="..."`

### ISSUE THREAD

**Issue by resistor4u** [davidgohel/officedown#57]
When passing `fig.scap` to `knitr::include_graphics()`, it would be valuable to have this item available and used in the List of Figures, and the same goes for `caption.short` with kable for List of Tables. Not sure if this is a bug or a feature request.

**Comment by davidgohel** [comment]
There is no `fig.scap` as argument for `knitr::include_graphics()`. Sorry, I don't know these options. 

It seems this is for latex, no?

**Comment by resistor4u** [comment]
yes, for latex but also for html and pdf writers, i believe.

**Comment by davidgohel** [comment]
Sorry, this package is only for Word and eventually PowerPoint. 

There is no broken support as it has never been a feature, sorry.

**Comment by resistor4u** [comment]
is there functionality to arbitrarily cut or curtail the amount of text that is drawn from figure captions and fed into the list of figures, tables?

**Comment by davidgohel** [comment]
if not documented, it does not exist `¯\_(ツ)_/¯ `
