### ISSUE TITLE
inconsistent use of reference_docx

### ISSUE THREAD

**Issue by resistor4u** [davidgohel/officedown#58]
In my Rmd, I cannot seem to get officedown to abide by the styles I set out in reference.docx, specifically numbered sections. The `numbersections: yes` bit in YAML below halts compilation with following:
```
---
bibliography: ../../full_zotero_bibliography.bib
fontfamily: times
lang: en-US
#numbersections: yes
output:
  #bookdown::word_document2
  officedown::rdocx_document:
    reference_docx: ../../reference.docx
    #numbersections: yes
---
```
Error:
```
Error in (function (toc = FALSE, toc_depth = 3, number_sections = FALSE,  : 
  unused argument (numbersections = TRUE)
Calls: <Anonymous> ... create_output_format -> do.call -> <Anonymous> -> do.call
Execution halted
```
That's all the info RStudio is giving me. But, the error is the same regardless of whether it's `numbersections` or `numberSections`, whether it's child of officedown::rdocx_document or same level. The Table of Contents generates correctly, but without level numbering, so I know the headers are correct. I also know the reference.docx is correctly styled, because bookdown::word_document2 correctly numbers sections. (But with bookdown::word_document2, there are no numbered pages! If you have insight about that, I'd like to hear it.)

**Comment by davidgohel** [comment]
The error you are getting are because you want to use arguments from other functions you are probably used to. This is not part of the arguments of `rdocx_document`. See https://davidgohel.github.io/officedown/reference/rdocx_document.html

You can read the user manual here: https://ardata-fr.github.io/officeverse/officedown-for-word.html

**Comment by resistor4u** [comment]
i've studied the docs closely, and recalled seeing that officedown follows bookdown syntax as nearly as possible, so i thought that extended also to yaml formatting.

**Comment by resistor4u** [comment]
i see now that it follows from rmarkdown's `number_sections` in lieu `numbersections`

**Comment by davidgohel** [comment]
You need to look at `rmarkdown::word_document` (the default base_format). rdocx_document pass arguments that it does not know to this function
