### ISSUE TITLE
Narrow margins

### ISSUE THREAD

**Issue by keithhurley** [davidgohel/officedown#6]
The readme mentions using narrow margins, but I can not find any example of how to do so.  Is this only possible with a reference document?

**Comment by davidgohel** [comment]
I will have a look, can't find it neither (and it's available in officer... I need to refresh my memory on this point)

**Comment by davidgohel** [comment]
This is how to do it with the last version:



```````
The following instructions define the section that applies to the text preceding
it up to the end of the previous section.

```{r}
ps <- prop_section(
  page_margins = page_mar(bottom = 1, top = 2, left = 1.5),
  type = "oddPage"
)
block_section(ps)
```
```````

See https://github.com/davidgohel/officedown/tree/master/inst/examples/bookdown for an example.

**Comment by littlehifive** [comment]
@davidgohel Hi, is there a way to apply the margin setting globally to the entire document that I am generating using `officedown`? Thanks!
