### ISSUE TITLE
How to customize cross reference using word labels and option to choose top or bottom for figures?

### ISSUE THREAD

**Issue by AlvaroMCMC** [davidgohel/officedown#64]
output file:
[word2.docx](https://github.com/davidgohel/officedown/files/6209212/word2.docx)
desired output file:
[word2 - copia.docx](https://github.com/davidgohel/officedown/files/6214502/word2.-.copia.docx)

1. The position of title figure could be on top and not only bottom. How can I do it?

![image](https://user-images.githubusercontent.com/21317475/112695858-cb0cac80-8e52-11eb-9f9f-89f99860af61.png)

2. being able to choose between different captions. In this example I am using "gráfico"
![image](https://user-images.githubusercontent.com/21317475/112696001-0909d080-8e53-11eb-8d65-fa6e7d6ba8b8.png)

3. Being able to cross reference the whole phrase "caption-number".
![image](https://user-images.githubusercontent.com/21317475/112696060-2b035300-8e53-11eb-8371-338475f7e9e0.png)

I don't know if they are possible to apply with officedown, in this case, please tell me how. Thanks.

I am using this code:
```
---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
library(officedown)
library(ggplot2)
```
````
```
## Figure

```{r fig.cap="economics plot", fig.id = "tsplot", fig.cap.style = "Image Caption"}
ggplot(economics, aes(date, unemploy / pop)) + 
  geom_line() + 
  theme_minimal()

```
## Tables

### economics

```{r tab.cap="economics table", tab.id = "mytab", tab.cap.style = "Table Caption"}
head(economics)

```
### mtcars

```{r tab.cap="mtcars table", tab.id = "mtcars", tab.cap.style = "Table Caption"}
head(mtcars)

```
## Cross-referencing

Figure and table have auto-numbered captions that can be cross referenced: 

* This is a linked reference to a figure \@ref(fig:tsplot), its number is computed by Word 
and it's linked to the corresponding graphic when clicking on it.
* This is a linked reference to a table \@ref(tab:mytab), its number is computed by Word 
and it's linked to the corresponding table when clicking on it. This is a linked reference to 
a table \@ref(tab:mtcars).

**Comment by davidgohel** [comment]
For the question 1: use knitr option, {officedown} tries to comply at maximum to knitr. 

```````
```{r fig.cap="economics plot", fig.id = "tsplot", fig.cap.style = "Image Caption", fig.topcaption = TRUE}
ggplot(economics, aes(date, unemploy / pop)) + 
  geom_line() + 
  theme_minimal()

```
```````

-----

For question 2, you can have a look at https://ardata-fr.github.io/officeverse/about-office-documents.html#what-is-a-word-sequence-identifier

So something like:

```
knitr::opts_chunk$set(fig.lp = "gráfico")
```

------


Question 3

You need to create your customized `run_autonum`. 

These could help, it goes further than your question, but you can pick up some code and adapt to your need: https://github.com/davidgohel/officedown/issues/60

The documentation will be augmented with more explanations and example later.
