### ISSUE TITLE
Images in page headers of reference docx

### ISSUE THREAD

**Issue by hmeleiro** [davidgohel/officedown#67]
I'm trying to knit a markdown with `officedown::rdocx_document` using a reference docx with an image in the page header. When knitting the markdown with regular `word_document` the header image is there, but when I use `officedown::rdocx_document` the header image is ignored. Is this normal? Does `officedown::rdocx_document` support images in the headers of reference docx's? Is there another way to add images in the page headers from the Rmd itself?

Here as example with the reference docx attached:

[reference.docx](https://github.com/davidgohel/officedown/files/6378199/reference.docx)

``````````
---
date: "`r Sys.Date()`"
author: "Your Name"
title: "officedown template"
output: 
  officedown::rdocx_document:
    reference_docx: reference.docx
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.cap = TRUE)
library(officedown)
library(officer)
library(flextable)

```

# Title
```{r}
flextable(head(iris))

```
``````````

**Comment by davidgohel** [comment]
Yes, users did want to be able to define page width, height, margins etc. I added this feature forgot to preserve header/footer. I will fix

**Comment by hmeleiro** [comment]
Thanks. And thank you again for the officeverse. It's really useful.

**Comment by davidgohel** [comment]
It's fixed now. Thanks to let me know about this issue

**Comment by hmeleiro** [comment]
That's great, David. Thanks to you for your work. I0m assuming it's on the github version, not CRAN yet, right?

**Comment by davidgohel** [comment]
Yes, it's only on github for now

**Comment by PHEindrakusuma** [comment]
Apologies David, I tried this with an image in the first page header and the GitHub version (0.2.3.001) does not seem to work. When I put the image in the default header it does work. Does this mean first page headers are not supported in officedown?

**Comment by davidgohel** [comment]
@PHEindrakusuma This issue is closed as it is fixed. I just retried the example upper, and it works as expected. Please provide a reproducible example in a new issue if you think you met a bug.
