### ISSUE TITLE
Preserve margins from template

### ISSUE THREAD

**Issue by camitz** [davidgohel/officedown#69]
As suggested by [yourself](https://github.com/davidgohel/officedown/issues/68#issuecomment-842313912) and option to preserve margins from the template. 

If you ask me, however, this should be the default behavior. Margins provided in preamble should everride template and there should not be defaults. That would also have the benefit of being the non-breaking alternative as of 0.2.1.

**Comment by davidgohel** [comment]
I agree, this is why I did not close #68

I'll make it the default
