### ISSUE TITLE
Yaml on section 2.1 (Templates) of the Officeverse ebook

### ISSUE THREAD

**Issue by brunolopesbr** [davidgohel/officedown#72]
On the section 2.1 of the book (https://ardata-fr.github.io/officeverse/office-documents-generation.html) the YAML reference for the creation of Powerpoint slides is:

---
date: "2020-15-36"
author: "Your Name"
title: "officedown template"
output: 
  officedown::rpptx_document:
    reference_docx: path/to/your/template.pptx
---

But the line

    reference_docx: path/to/your/template.pptx
    
should be 

    reference_doc: path/to/your/template.pptx

(note the  **reference_doc::**, not reference_docx:)

**Comment by davidgohel** [comment]
Thanks, it's fixed and will be soon online
