### ISSUE TITLE
'Different first page' header setting ignored

### ISSUE THREAD

**Issue by casblaauw** [davidgohel/officedown#75]
## Problem
First of all, thanks for your great package! We've been using it for a while to great effect. 
Some time ago, however, something that used to work broke: our separate first page header (as defined in our template docx file) was not considered anymore in newly knitted files. The file still knew about the separate first page header, but the 'Different First Page' checkbox in Word's 'Header & Footer' settings was unchecked in the knitted file, even though it is checked in the template file (and used to work fine). I'm sorry for creating another bug report about this function, but it seems to be unrelated to #35 or #39.

## Possible cause
After digging through some old reports, it seems like this change happened on our side between the 28th of April and the 4th of May. I can't say for sure whether it's the cause, but that lead me to [this commit](https://github.com/davidgohel/officedown/commit/f3be4742db1615967b6120b8466c7c9babc4450e), from 1 May, which is the one that fixed #67.

## Reprex

````
---
title: "test1"
output: 
  officedown::rdocx_document:
    reference_docx: test_template.docx
---

```{r setup, include=FALSE}
library(officedown)
library(officer)
```

This is some random text just to have something.

\newpage

This is even more text, but now on the second page.
````
You can find the template I used and the resulting output [here](https://drive.google.com/drive/folders/1-k5NBA2_gaW74UvDz98fJK9U9-4D7Ljf?usp=sharing). It can also easily be done by hand by creating an otherwise empty word template file which has a different first header and then something in the normal header as well.

This is the resulting file, which does not show the distinct first header by default, even though the template did:
![image](https://user-images.githubusercontent.com/38132585/125261315-6e4dd880-e301-11eb-842f-577ce8297b8c.png)

Ticking the box then does show the header we want on the first page:
![image](https://user-images.githubusercontent.com/38132585/125261433-8de50100-e301-11eb-87aa-940e0d7a8b3b.png)

## Session info
````
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7           digest_0.6.27        R6_2.5.0             officedown_0.2.3.001 evaluate_0.14       
 [6] zip_2.2.0            gdtools_0.2.3        rlang_0.4.11         cachem_1.0.5         uuid_0.1-4          
[11] xml2_1.3.2           rmarkdown_2.9        tools_4.0.4          officer_0.3.19.005   fastmap_1.1.0       
[16] xfun_0.24            yaml_2.2.1           compiler_4.0.4       systemfonts_1.0.2    rvg_0.2.5           
[21] memoise_2.0.0        htmltools_0.5.1.1    knitr_1.33   
````

**Comment by Michael-Stevens-27** [comment]
Hello! 

I'm having the exact same problem as neatly described above. 

A potential work around is as you alluded to, by installing an earlier version of the package prior to May 1st. After some tinkering I found that installing the package associated with the commit 1a0924cd3699a7571ba1ff78745a14e3459288eb from March 14th resolves this problem with creating these first-page headers and footers.

`devtools::install_github("davidgohel/officedown@1a0924cd3699a7571ba1ff78745a14e3459288eb")`

Hope this helps!

**Comment by MattCowgill** [comment]
I just came here to say I am encountering the same issue, and that installing from the specific commit as above fixes it for me.

**Comment by davidgohel** [comment]
Sorry for the delay...

It should be fixed now. You will need to update 'officer' with the dev version (where the problem was) and 'officedown' (recently updated). It should be on CRAN in two weeks.


```
remotes::install_github("davidgohel/officer")
remotes::install_github("davidgohel/officedown")
```


You can see a simple 'R Markdown' example here: https://github.com/davidgohel/officedown/blob/483e5383993024ed542fc57407279a630441ee90/tests/testthat/rmd/sections.Rmd and the expected output here:  

![](https://github.com/davidgohel/officedown/raw/483e5383993024ed542fc57407279a630441ee90/tests/testthat/_snaps/rdocx-sections/docx-sections.png)

**Comment by MattCowgill** [comment]
Thank you @davidgohel, and thanks for your excellent packages
