### ISSUE TITLE
number_section and markdown_document2: change of default behavior not possible

### ISSUE THREAD

**Issue by Pindar777** [davidgohel/officedown#77]
After updating GNU R to 4.1.0. I noticed that in rdocx the `number_section: TRUE` parameter has no effect anymore.
With bookdown::word_document2 is is still working.

```
---
title: number_section with rdocx_document
subtitle: not working with R-4.1.0
output:
   bookdown::markdown_document2:
     base_format: officedown::rdocx_document
     number_section: TRUE
     fig_caption: TRUE
---

# This is the first Headline &minus; should be auto-numbered

That is not the case with current officedown and R-4.1.0, but is working with current bookdown
and R-4.1.0
```

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C
[5] LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        magrittr_2.0.1    knitr_1.33        xml2_1.3.2
 [5] uuid_0.1-4        R6_2.5.0          rlang_0.4.11      fastmap_1.1.0
 [9] stringr_1.4.0     tools_4.1.0       xfun_0.24         rvg_0.2.5
[13] htmltools_0.5.1.1 systemfonts_1.0.2 yaml_2.2.1        digest_0.6.27
[17] officedown_0.2.2  bookdown_0.22     zip_2.2.0         officer_0.3.19
[21] memoise_2.0.0     cachem_1.0.5      evaluate_0.14     rmarkdown_2.9
[25] stringi_1.6.2     compiler_4.1.0    gdtools_0.2.3     jsonlite_1.7.2

```

**Comment by davidgohel** [comment]
Hello,

I am confused :)

You are talking about https://github.com/davidgohel/officedown/blob/master/NEWS.md#issues-1

You were in the discussion: https://github.com/davidgohel/officedown/issues/59

Could you explain what you want to achieve?

**Comment by Pindar777** [comment]
Dear @davidgohel,

Thanks for your fast response. Let me clarify.
IMHO the discussion was about the default behavior of `number_section` in terms of `bookdown::markdown_document2` usage with `officedowm`. I want /need to manually switch this paramater to `TRUE` since I don't want to make use of the auto_numbers instead of format style in word. And that is somehow not working anymore after installing R-4.1.0 (upgrade of R 4.0.4 for me).

Cheers

**Comment by davidgohel** [comment]
This is not possible since #59 and this is not related to R-4.1.0.

**Comment by Pindar777** [comment]
@davidgohel yes, I thought I already used a new version of officedown with R 4.0.4.

I change the title of the issue.

However, is is possible to allow overwriting of the default dealt by #59

**Comment by davidgohel** [comment]
Sorry, I just decided I need a break from github. 

I don't want to argue. Closing that issue for now, this won't happen now. Maybe later.
