### ISSUE TITLE
Math expression

### ISSUE THREAD

**Issue by estedeahora** [davidgohel/officedown#80]
Hello,

I have a problem with the use of `\Bigl` in math equations when I use officedown::rdocx_document in my YAML output.
Here is a reproducible example:
```
---
title: "Title"
output: 
  officedown::rdocx_document
  # html_document
---

## Example

This is the Dissimilarity Index equation (D).

$$
D_{k_1,k_2} = \frac{1}{2}.\sum_{i=1}^n\Bigl\lvert{\frac{x_i^{k_1}}{X^{k_1}}-\frac{x_i^{k_2}}{X^{k_2}}}\Bigl\rvert
$$
```

The result obtained in Word is as follows:

![image](https://user-images.githubusercontent.com/56130517/142643335-fbec389e-f3fa-42b7-9ae5-c06e38d05201.png)

and the render output indicates the following warning:

![image](https://user-images.githubusercontent.com/56130517/142643549-9307d30a-f6a3-436a-bae7-a0f4669b58d8.png)

The knit works with output: html_document

My R session information:

```
sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 22000)
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=Spanish_Argentina.1252  LC_CTYPE=Spanish_Argentina.1252   
# [3] LC_MONETARY=Spanish_Argentina.1252 LC_NUMERIC=C                      
# [5] LC_TIME=Spanish_Argentina.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# loaded via a namespace (and not attached):
#   [1] compiler_4.1.2 tools_4.1.2   
```

**Comment by davidgohel** [comment]
I can't see anything relative to officedown in the `sessionInfo()`. However, this is not relative to officedown - it also happens with `word_document` (used by rdocx_document). 

I don't know a lot about writing equations - maybe it's a pandoc limit. But it's not an issue with officedown
