### ISSUE TITLE
Help with using flextable in officedown

### ISSUE THREAD

**Issue by xiaochi-liu** [davidgohel/officedown#82]
Hello, it seems that there's a problem when using `flextable` in `officedown`: the caption appears at the bottom of the table, and the suffix for numbering chunk (“:”) can't be changed.

I prepared a piece of code to reproduce the problem:

``````
---
output: 
  officedown::rdocx_document:
    tables:
      caption:
        sep: '. '
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.cap = TRUE,
	message = FALSE,
	warning = FALSE
)
library(officedown)
library(officer)
library(flextable)
library(tidyverse)
```

```{r}
tribble(
  ~ model, ~ column_1, ~ column_2,
  "GLM", "1", "25",
  "RF", "1", "25",
  "XRT", "1", "25"
  ) %>% 
  flextable() %>% 
  set_caption("Models trained and evaluated during multiple algorithms assessment.",
              autonum = run_autonum(seq_id = "tab", bkm = "models"))
```
``````
It would be rendered as:

![image](https://user-images.githubusercontent.com/48895627/145673009-ca841f8e-ac2b-47fa-a4ac-1474ddebd570.png)

I was wondering, how to make the caption above the table, and use ". " as the suffix of number?

Your kind guidance is much appreciated!

``` r
library(officedown)
library(officer)
library(flextable)
library(tidyverse)
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] forcats_0.5.1      stringr_1.4.0.9000 dplyr_1.0.7        purrr_0.3.4       
#>  [5] readr_2.0.2        tidyr_1.1.4        tibble_3.1.5       ggplot2_3.3.5     
#>  [9] tidyverse_1.3.1    flextable_0.6.9    officer_0.4.2.001  officedown_0.2.3  
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.7        lubridate_1.7.10  assertthat_0.2.1  digest_0.6.28    
#>  [5] utf8_1.2.2        cellranger_1.1.0  R6_2.5.1          backports_1.3.0  
#>  [9] reprex_2.0.1      evaluate_0.14     httr_1.4.2        highr_0.9        
#> [13] pillar_1.6.4      gdtools_0.2.3     rlang_0.4.12      readxl_1.3.1     
#> [17] uuid_1.0-3        rstudioapi_0.13   data.table_1.14.2 rmarkdown_2.11   
#> [21] munsell_0.5.0     broom_0.7.10      compiler_4.0.3    modelr_0.1.8     
#> [25] xfun_0.28         pkgconfig_2.0.3   systemfonts_1.0.2 base64enc_0.1-3  
#> [29] rvg_0.2.5         htmltools_0.5.2   tidyselect_1.1.1  fansi_0.5.0      
#> [33] crayon_1.4.2      tzdb_0.1.2        dbplyr_2.1.1      withr_2.4.2      
#> [37] grid_4.0.3        jsonlite_1.7.2    gtable_0.3.0      lifecycle_1.0.1  
#> [41] DBI_1.1.1         magrittr_2.0.1    scales_1.1.1      zip_2.2.0        
#> [45] cli_3.1.0         stringi_1.7.5     cachem_1.0.6      fs_1.5.0         
#> [49] xml2_1.3.2        ellipsis_0.3.2    generics_0.1.1    vctrs_0.3.8      
#> [53] tools_4.0.3       glue_1.5.0        hms_1.1.1         fastmap_1.1.0    
#> [57] yaml_2.2.1        colorspace_2.0-2  rvest_1.0.1       memoise_2.0.1    
#> [61] knitr_1.36        haven_2.4.3
```

<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mps9506** [comment]
To get the caption on top you can set the following knitr chunk option:

```r
knitr::opts_chunk$set(tab.topcaption = TRUE)
```

I'm not sure how to deal with the separator. I've been running into similar issues. The yaml and knitr chunk options for the separator work with other tables but don't seem to impact flextable captions.

**Comment by bishun945** [comment]
I ran into the same issue. 

To let the caption at the top, the answer by @mps9506 is right. And you can also put it into your YAML at the head of RMD file.

Another issue I found is when inserting a cross reference in the context, like `\@ref(tab:tab1)`. It will be knitted as `Table 1:`. The separator `:` can not be removed or changed.

**Comment by bishun945** [comment]
Hi @mps9506 ,

Thanks for the post. Your demo runs all well from my side.

And sorry for that I forgot to post my testing code. I just realize I am using `bookdown::markdown_document2:` as an output with `base_format: officedown::rdocx_document`. When comes like this, the issue remains. 

Here is the example.

````
---
output: 
  # officedown::rdocx_document:
  bookdown::markdown_document2:
    base_format: officedown::rdocx_document
    tables:
      style: Table
      layout: autofit
      width: 1.0
      topcaption: true
      tab.lp: 'tab:'
      caption:
        style: Table Caption
        pre: 'Table '
        sep: '. '
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = FALSE)
---

```{r setup, include=FALSE}
## load libraries
library(officer)
library(officedown)
library(flextable)
```

This is an example of an unformatted table and how we cross-reference that table ([Table \@ref(tab:mtcars)](#tab:mtcars)).

```{r tab.cap='this is the builtin mtcars data.', tab.id='mtcars'}
dat <- mtcars
head(dat, n = 10)
```

The [`flextable`](https://davidgohel.github.io/flextable/) package provides additional formatting flexibility when exporting to 
Word (Table \@ref(tab:mtcarsflex)).

```{r tab.cap='flextable formatted table.', tab.id='mtcarsflex'}
ft <- flextable(head(dat, n = 10))
ft
```

````

Then, it returns a `Table Table 1:` in the second paragraph.

So, it seems an issue for using `bookdown::markdown_document2`.

Regards,
Shun

**Comment by xiaochi-liu** [comment]
Thank you so much @mps9506 and @bishun945. According to your guidance, the caption has moved to the top of the table and the separator has become "."

However, here comes another problem. In order to get a caption style like "**Table 1**. This is the builtin mtcars data", I change the last line of YAML header in your demo: `fp_text: !expr officer::fp_text_lite(bold = TRUE)`. However, this only changes table 1 but not table 2:
![image](https://user-images.githubusercontent.com/48895627/153781521-e6138624-20ed-43d4-a0be-b85bb2f05561.png)

![image](https://user-images.githubusercontent.com/48895627/153781543-6f8ccc22-0d3a-477e-99b9-0e447a651fe4.png)

May I know how to solve this problem? The demo codes are here:

``````
---
output: 
  officedown::rdocx_document:
    #reference_docx: format.docx
    tables:
      style: Table
      layout: autofit
      width: 1.0
      topcaption: true
      tab.lp: 'tab:'
      caption:
        style: Table Caption
        pre: 'Table '
        sep: '. '
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
---

```{r setup, include=FALSE}
## load libraries
library(officer)
library(officedown)
library(flextable)
```

This is an example of an unformatted table and how we cross-reference that table ([Table \@ref(tab:mtcars)](#tab:mtcars)).

```{r tab.cap='this is the builtin mtcars data.', tab.id='mtcars'}
dat <- mtcars
head(dat, n = 10)
```

The [`flextable`](https://davidgohel.github.io/flextable/) package provides additional formatting flexibility when exporting to 
Word (Table \@ref(tab:mtcarsflex)).

```{r tab.cap='flextable formatted table.', tab.id='mtcarsflex'}
ft <- flextable(head(dat, n = 10))
ft
```
``````

Your kind guidance is much appreciated!

**Comment by davidgohel** [comment]
## Declared bug num 1

> there's a problem when using flextable in officedown: the caption appears at the bottom of the table, and the suffix for numbering chunk (“:”) can't be changed.

I can't believe this is perceived as a bug! This is documented in many places: 

* https://ardata-fr.github.io/flextable-book/captions-and-cross-references.html#knitr-chunk-options-for-flextable-captions
* in R help `?officedown::rdocx_document`
* https://ardata-fr.github.io/officeverse/officedown-for-word.html#caption-label-for-figures-and-tables

**Comment by davidgohel** [comment]
## Declared bug num 2

> So, it seems an issue for using bookdown::markdown_document2... [EDIT]: Table Table 1: is found in flextable table but not in a "normal" one in the first chunk.

@bishun945, OK, the workaround was to not write "Table" but if you want to write it... the simpler is to remove that functionality.

**Comment by davidgohel** [comment]
## Declared bug num 3

<img width="1308" alt="Capture d’écran 2022-03-04 à 16 48 48" src="https://user-images.githubusercontent.com/4331618/156795264-bc458004-06b8-4279-a2ca-febe6613777b.png">


@xiaochi-liu not reproducible

**Comment by davidgohel** [comment]
It seems to me these are not bugs related to officedown, but questions/support requests. If a new answer is given, a new question is asked. That's why I am closing that issue.

Also, it doesn't seem reasonable to ask for help by reporting bugs that aren't bugs rather than reading the documentation. I lose in average an hour per question, This one cost 2 hours roughly! Questions have been most often documented. This time is wasted for me and for you. 

That's why I am going to close the "Issue" tab, this is going to be the second time in the last year - I don't think I will reopen it before a long time. I am loosing a lot of time on this and I want this to stop. 

Users will be able to discuss in the "discussions" tab. (don't send me PM asking free support, I ignore and delete them).

**Comment by davidgohel** [comment]
https://github.com/davidgohel/officedown/discussions
