### ISSUE TITLE
(How to) Add footnotes through officedown

### ISSUE THREAD

**Issue by paurrodri** [davidgohel/officedown#84]
Hi, 

Is it possible to add footnotes to a Word document with officedown? I am aware that `run_footnote()` function exists in officer, but I have not found documentation about how to use it, or about how to use it with officedown in a Rmarkdown. 

Thank you!

**Comment by davidgohel** [comment]
Hello

Yes

The documentation you are asking for is there

https://ardata-fr.github.io/officeverse/officedown-for-word.html#insert-formatted-texts
