### ISSUE TITLE
Fields Word document

### ISSUE THREAD

**Issue by sebastianottmann** [davidgohel/officedown#86]
Thank you for the great package.
I include a cover page in my markdown file, which is a separate Word file. Is there a possibility to define a field in the cover sheet (Word doc) which is then replaced by a value from my R markdown file (e.g., the number of participants in the survey)?

**Comment by resistor4u** [comment]
When I knit a set of Rmd, this works for me:
````
```{r pouring}
officer::block_pour_docx("templates/my_titlepage.docx")
```
````
