### ISSUE TITLE
`rpptx_document` does not use the assigned layout in code chunk

### ISSUE THREAD

**Issue by jack-gregory** [davidgohel/officedown#90]
Salut David, merci beaucoup pour tout votre travail ici!  Et pardon, mais c'est plus facile pour moi d'expliquer en anglais.

I seem to be having a similar issue to #32, though it's possible that I've misunderstood the discussion there.  Regardless, I was hoping you may be able to clarify some things for me.

When I knit an `officedown::rpptx_document`, none of the specified layouts in the code chunks actually appear in the generated pptx document.  As a minimal reproducible example, I've adapted your [minimal_powerpoint.Rmd](https://github.com/davidgohel/officedown/blob/master/inst/examples/minimal_powerpoint.Rmd).  In the code below, the first slide has been assigned a 'Two Content' layout, while the second has been assigned a 'Blank' layout.  However, as can be seen in the images below, when I knit the document, the resulting file only produces 'Title and Content' slides.

````
---
date: "`r Sys.Date()`"
author: "Your Name"
title: "Untitled"
output: 
  officedown::rpptx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE)
library(officedown)
library(ggplot2)
library(rvg)
```

## Table

```{r layout='Two Content', ph=officer::ph_location_left()}
head(cars)
```

```{r layout='Two Content', ph=officer::ph_location_right()}
head(iris)
```

## Slide with Plot

```{r plot1, layout='Blank', ph=officer::ph_location_fullsize()}
dml(plot(pressure))
```
````

**Table**

![image](https://user-images.githubusercontent.com/77354448/192327613-1c29c288-60e1-4c6b-9b87-ead5e5a99894.png)

**Slide with Plot**

![image](https://user-images.githubusercontent.com/77354448/192327787-9a1bbe78-0526-4595-9df0-f1c48a2f2e60.png)

I also tried manipulating the layout in the yaml:

```
---
date: "`r Sys.Date()`"
author: "Your Name"
title: "Untitled"
output: 
  officedown::rpptx_document:
    layout: "Two Content"
---
```

However, it produces identical results to those pictured above.  Is the the expected behaviour?  If so, how can I assign the desired layout from a pptx template to a slide in Rmarkdown?  And if not, I've provided my session info below in case this is a bug.

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_1.1.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        bookdown_0.27     digest_0.6.29     R6_2.5.1          officedown_0.2.4  evaluate_0.15     zip_2.2.0         gdtools_0.2.4    
 [9] cachem_1.0.6      rlang_1.0.2       cli_3.3.0         uuid_1.1-0        xml2_1.3.3        rmarkdown_2.14    tools_4.2.0       officer_0.4.4    
[17] xfun_0.30         yaml_2.3.5        fastmap_1.1.0     compiler_4.2.0    systemfonts_1.0.4 sessioninfo_1.2.2 rvg_0.2.5         memoise_2.0.1    
[25] htmltools_0.5.2   knitr_1.39
```

**Comment by davidgohel** [comment]
From the reference discussion

> Using layout='Two Content', ph=officer::ph_location_left() in chunk options is like "use properties defined in left placeholder of the layout two content".

We can't force Pandoc to change layout, the used layout is managed by pandoc, But we can use properties of other layouts. That's what is implemented until now.

> However, it produces identical results to those pictured above. Is the the expected behaviour? 

yes

> If so, how can I assign the desired layout from a pptx template to a slide in Rmarkdown? 

you can't with officedown, maybe you could find a way of doing it in pure pandoc.

> And if not, I've provided my session info below in case this is a bug.

Not a bug :)

There are only two features for PPTX: https://github.com/davidgohel/officedown#powerpoint

- [...] providing a mechanism for placing results according to the slide template contained in the PowerPoint document used as “reference_doc”.
- [...] possibility to transform your graphic instructions into editable vector graphics

**Comment by jack-gregory** [comment]
Thanks David!  Much appreciated.  I thought that may be the case, but it's helpful to have it confirmed.

As an FYI and for anyone else with a similar question, assigning a layout to a slide is now a feature available in quarto pptx documents.  You can see the documentation [here](https://quarto.org/docs/presentations/powerpoint.html#slide-layouts).

**Comment by davidgohel** [comment]
thank you for this information!

'officedown' will not evolve anymore on pptx output (unless a bug to solve) and Quarto should be used instead.
