### ISSUE TITLE
accessing different parts of word doc

### ISSUE THREAD

**Issue by jic007** [davidgohel/officedown#91]
hi I have been searching for the following and wonder if you could help/develop:

- creating special pages e.g. cover page and section divider where you would have a title and whatever other line of text
-  if you were to add shapes to the margin to highlight some facts like in business reports, how to access that shape to add text to

**Comment by davidgohel** [comment]
Hi,

1. See `officer::block_pour_docx()` or read the manual here: https://ardata-fr.github.io/officeverse/officedown-for-word.html#embbed-word-document
2. Not a feature.

**Comment by jic007** [comment]
Hey David,
thank you for this. I have been reading around officedown but never found a reseouce to tell me how to access margins if I want to write in them or for example if I were to create shapes in the template reference document and want to use the same page and add text. I am trying to use for example some of the ready made ones in word document templates for example business reports

**Comment by davidgohel** [comment]
When something is not documented, it means it is not a feature.
