### ISSUE TITLE
Extra section break is created after MULTCOLUM stop

### ISSUE THREAD

**Issue by ausfas** [davidgohel/officedown#93]
```
<!---BLOCK_MULTICOL_START--->
```
   blahhhh
```
<!---BLOCK_MULTICOL_STOP{widths: [4,3], space: 0.2, sep: false}--->
```
Any text......

The work document adds an extra section break(next page) after the MULTICOULMN STOP. 
The example on the website works because it has another section that is LANDSCAPE START. However, if we remove the LANDSCAPE start (to keep in the portrait then you'll see the same behaviour that the text come after section break next page, same behaviour is observed.

The text should start immediately on the same page once two column is finished.

**Comment by davidgohel** [comment]
What if you use `block_section()` as illustrated here: https://ardata-fr.github.io/officeverse/officedown-for-word.html#function-block_section

**Comment by ausfas** [comment]
I've tried that but it applies a break after continue section
:::::::::::::::::section Break (continuous):::::::::::::::::
:::::::::::::::::::Section Break (Next Page)::::::::::::::::::::::::::
Section break at the end is what causing this issue that is automatically inserted by the 
 if it is not followed by 

Could you please check what is the code doing once  is inserted ?
I expect the flow show be either section continue or nothing but BLOCK_MULTICOL_STOP code needs to be fixed.

**Comment by davidgohel** [comment]
Thanks, it's fixed now. You will need to update officer with the dev version (`remotes::install_github("davidgohel/officer")`). It will be on cran in two weeks

**Comment by ausfas** [comment]
Thanks David,
I'm on leave will test it next week.

**Comment by davidgohel** [comment]
no problem @ausfas , it's on CRAN now and I think it's working.
