### ISSUE TITLE
dml bg is always "white" in R Markdown

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [davidgohel/officedown#95]
Many thanks for the officeverse packages. I noticed that in R Markdown PowerPoint the rvg::dml `bg` argument seems ignored. I could confirm it is functional when directly using officer calls as in the documentation to create the PowerPoint and not when using R Markdown.

**reprex**: with RStudio, create a new R markdown document from template "Advanced PowerPoint presentation {officedown}". Simply add the argument `bg="wheat"` to the `dml` calls as per rvg::dml documentation and knit. No background coloring will show.

Some further experimenting with a truly transparent ggplot theme and setting the slide background to non-white seems to indicate the generated plots always have a "white" background if rvg::dml is used in R Markdown context. Now I'm not interested in "wheat" but rather "transparent" and this does work when using officer directly, but that is not our preferred way of generating PowerPoint presentations.

    R version 4.1.3 (2022-03-10)

    Package    Version
    officedown 0.2.4  
    officer    0.4.4  
    rvg        0.2.5

**Comment by davidgohel** [comment]
thanks for reporting this, it's been fixed
