### ISSUE TITLE
Images in page headers of reference docx misplaced when using  <!---BLOCK_LANDSCAPE_START---> <!---BLOCK_LANDSCAPE_STOP--->

### ISSUE THREAD

**Issue by YoJimboDurant** [davidgohel/officedown#99]
When adding `<!---BLOCK_LANDSCAPE_START--->` and `<!---BLOCK_LANDSCAPE_STOP--->` to the example in https://github.com/davidgohel/officedown/issues/67, the logo in the reference document header appears in the section below the  `<!---BLOCK_LANDSCAPE_STOP--->`.

# Reproducible Example

Using 
[reference.docx](https://github.com/davidgohel/officedown/files/10456877/reference.docx)
as example document, and the following Rmd:

````
---
date: "`r Sys.Date()`"
author: "Your Name"
title: "officedown template"
output: 
  officedown::rdocx_document:
    reference_docx: reference.docx
---
  
  
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.cap = TRUE)
library(officedown)
library(officer)
library(flextable)

```

# Title
```{r}
flextable(head(iris))
```


<!---BLOCK_LANDSCAPE_START--->
```{r}
plot(rlnorm(100), rlnorm(100))
```
<!---BLOCK_LANDSCAPE_STOP--->

More text is here
````

Results in the logo appearing on page 3: 

![Capture](https://user-images.githubusercontent.com/5215698/213449445-c5f37ab5-bdec-4143-83f2-68bb3e925522.PNG)

I attempted the approach using https://github.com/davidgohel/officedown/issues/75, but could not get image to appear inside the header.

**Comment by blechturm** [comment]
A similar thing happens if you use   

or this chunk from the demo bookdown files:

```
```{r}
ps <- prop_section(
  page_margins = page_mar(bottom = 1, top = 2, left = 1.5),
  type = "oddPage"
)
block_section(ps)
```

```

In both cases the header image disappears completely from all pages.

**Comment by davidgohel** [comment]
By using `<!---BLOCK_LANDSCAPE_START--->`, you added a section with no header and footer, that's what you see in the upper document. If you want to add headers and footers, you can do it by using `prop_section()` as mentioned. The last example shown in the documentation of `prop_section()` shows this.

See also https://ardata-fr.github.io/officeverse/officedown-for-word.html#function-block_section

Maybe also this SO will helps to understand how to add Word sections: https://stackoverflow.com/a/75451251/3315962
